### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by aiwaki** [Jleagle/steam-go#2]
Could you add some examples?

**Comment by Jleagle** [comment]
Hi, what would you like an example of?

**Comment by aiwaki** [comment]
I'm looking at [steam_test.go](https://github.com/Jleagle/steam-go/blob/master/steamapi/steam_test.go) but I don't quite understand how to get my account information (like by key or session).

Also, the **GetWishlist** function returns the error `json: cannot unmarshal string into Go struct field .subs.price of type int`.

**Comment by Jleagle** [comment]
For calls that hit the api you will need a key but store calls should always work.

The wishlist call was broken as Steam changed their JSON but that's just been fixed.

```
c := steamapi.NewClient()
c.SetKey(apiKey)

wishlist, err := c.GetWishlist(76561197973834076)
```
